### ISSUE TITLE
Listen.moe does not display song metadata in 3rd-party radio apps.

### ISSUE THREAD

**Issue by ghost** [LISTEN-moe/feedback#32]
**Please describe the problem you are having in as much detail as possible:**

In 3rd-party generic internet-radio apps that connect straight to stream URLs instead of going through Listen.moe API, song names and artists are not displayed.

When connect to Listen.moe
![listen](https://user-images.githubusercontent.com/73825967/127222368-ad3d9cae-249b-4050-891a-d590b4112591.png)

When connect to another radio:
![anison](https://user-images.githubusercontent.com/73825967/127222498-2386c068-4ecc-461f-9c96-83898425e0b4.png)

This is probably caused by Listen.moe not including metadata tags in stream URL (or something like that, I'm not an expert). I would like to request Listen.moe devs to make the site more friendly to 3rd party radio apps.

- App tested: [RadioDroid](https://f-droid.org/en/packages/net.programmierecke.radiodroid2/), [Transistor](https://f-droid.org/en/packages/org.y20k.transistor/)
- Operating system: Android.
- Stream URL: https://listen.moe/stream, https://listen.moe/opus

**Comment by ghost** [comment]
I wonder if anyone even read this.

**Comment by Pitu** [comment]
Unfortunately, metadata is not carried on the stream itself and that's why we provide it over WebSocket.
There are no plans to change this in the near future.

**Comment by ghost** [comment]
> Unfortunately, metadata is not carried on the stream itself and that's why we provide it over WebSocket. There are no plans to change this in the near future.

Then how do other radio stations do this? Not just anime station but every other music stations.

**Comment by Pitu** [comment]
> > Unfortunately, metadata is not carried on the stream itself and that's why we provide it over WebSocket. There are no plans to change this in the near future.
> 
> Then how do other radio stations do this? Not just anime station but every other music stations.

Oh I'm not saying it's not possible, I'm saying we don't do it. And probably won't in the near future.

**Comment by ghost** [comment]
Okay then...

**Comment by folliehiyuki** [comment]
> Unfortunately, metadata is not carried on the stream itself and that's why we provide it over WebSocket.
There are no plans to change this in the near future.

The docs website states that metadata is available for Vorbis stream right on the front page https://docs.listen.moe/ (in the Tip section).

A quick run of `ffplay` shows that metadata is indeed there:
```bash
$ ffplay https://listen.moe/stream
...
Input #0, ogg, from 'https://listen.moe/stream':B sq=    0B f=0/0   
  Metadata:
    icy-br          : 256
    icy-description : Delivering the best Japanese and Anime music around the globe!
    icy-genre       : Anime,Jpop,Japan,Asia,Asian
    icy-name        : LISTEN.moe
    icy-pub         : 1
    icy-url         : https://listen.moe
  Duration: N/A, start: 256.569333, bitrate: 256 kb/s
  Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 256 kb/s
    Metadata:
      track           : 3
      comment         : https://hikarinoakari.com
      genre           : J-Pop
      title           : いやいいや
      artist          : 當山みれい
      year            : 2021
      date            : 2021
      album           : still
      ENCODER         : Liquidsoap/1.3.7 (Unix; OCaml 4.07.1)
 258.83 M-A: -0.000 fd=   0 aq=   34KB vq=    0KB sq=    0B f=0/0
```

The `icy-*` fields are correctly picked up by most Internet radio apps. Here is a screenshot inside [pyradio](https://github.com/coderholic/pyradio):

![2022-09-26-235113_grim](https://user-images.githubusercontent.com/67634026/192335565-9b6ca9aa-aae3-456b-b502-b371cd401a04.png)

 For some reasons the specification for available fields are really scarce. Here are some documents I could find:
- https://cast.readme.io/docs/icy
- https://icecast.org/docs/icecast-2.4.1/server-stats.html
- https://web.archive.org/web/20190520053952/http://www.smackfu.com/stuff/programming/shoutcast.html

From a couple of radio streams I regularly listen to, the consensus seems to be providing `icy-title` field (corresponding to `StreamTitle` in the 3rd link above) either in `<artist> - <song_title>` or `<song_title> - <artist>` format. Some examples are:
- http://listen.rusongs.ru/ru-mp3-128
- https://otsu.s04.radio-tochka.com:5475/mount

Since all the common fields are already presented, I don't think adding another one would hurt.

**Comment by Pitu** [comment]
> The docs website states that metadata is available for Vorbis stream right on the front page https://docs.listen.moe/ (in the Tip section).

That's true, my comment was aimed more at the other streams which are more widely used. While some stream data is carried over in the vorbis stream is not complete and not something we are actively maintaining since most of our apps support WebSockets which gives much more and richer information.
